language: java

jobs:
  include:
    - stage: GitHub Release
      script: skip
      deploy:
        provider: releases
        api_key: "$GH_TOKEN"
        file: pom.xml
        skip_cleanup: true
        on:
          branch: setup-ci
