language: java
deploy:
  provider: releases
  api_key:
    secure: BvlX1t8ne8CyNgafat6OQp7EPb2t1sHHsQ3Tht2Z8N7x9zx+1AHFEvrP6agwEe7r5BsXAz43xAidNy2X8d391sL+kSBSL+rpJcL5fpcpUbAOWG5xsPhyVwhMfYJr96rljUcMar2l/twjDkXi83yLfAoYHXkfIwWG7BUrkvcB/w/1Pa5LvMcwOiwykd7DhEIMuGbhEyt+uj6Ctc6OM56TRYkLnHweyVgwrrHVfx5hA/cWLc+6yKZQpC94LdNDUAixV2DaLJQgzt1SXqi/0uhAut12bz3QvVJr8B9vhqxO5OO0UyMbySQdNSXJ5vMV11CVogu51iwl1rkQ4gzP2bWA69f4VwdKNj0OfWpPQs5nSTR1zJIwlz07R/BEBpqfPMpN8d+xYZqlmP+eiB4dVm0jDgl/d0EpniRdD5V7m7/Ah5TA7uc1NtwZXHXpD0M4i+y+BComDmJglF99I1C0TV0B6rd7NueYQF5LZans7MGRkpmuUMk+vM+3K4MYZt/1JUqfYfopWflhoKn6gVQvrJwIdneUTgnYk2hG4NbOAdc/YGnuIim0lZgQ9nKYt249x8A69lwfS/qfLUuYaTsogjG6YUtvXAgqoB88+GgSmXLP+GkNPuKlnWPwTAJWu8Z5uwYq1LG0InHxrmBMx6hn9rZD/nUSOHKF8OdYuxyoGfpVx2M=
  file: pom.xml
  on:
    branch: setup-ci
