language: java

deploy:
  provider: releases
  api_key:
    secure: cvCyNF3Pj6SYKK+Qabwc8pirdHyM4q7s1tca9s+Lzo9pujcCmYrrMuFbkiZZVDjSRer5BsJVosNfxA0304qNkm6oqa9XDMb97D1sja6aLFTAVfUBxGqEADrBXgkSPhNfW/hXLU6gQhXkAxHUM+YqN/nB53eXFXAHRVpdxX7xzPnH0R0VS54+Gsj42douybqzO18g2FDKZluHCJaUoSE0VccMAYg6Rr4mulRODBLGngjfvMTcY/ZVlsW0xemb/Uk77/qW/MhJtY/1ctMAHsQNYmyM3pxrhnfSBWLbdxldbS5/ZzvrFsCmNImSxDIbKo5sgdQrERWQ44BVTf2xIgjuGEUlA/OXPXAXtR1r+P9lHWTGoD3Nt7vtVbz6r393gcEvl7Oj4Teqymjj2LhHrHigkghiv45zNDzIKifHB/e0i57z3dpeBbKf3njD0LQOZgXbH8QuRC3hXhIPbhLBUDkHN8Gcl38ydEiJ/1WMT06fDUzMPmIx395xDefXEVNYSXhu7iJPVQ0kX9ZXUGm3WFHg1i0CXbQcuZPQNimBPh9AZyaMkTpktmxiFYcqAD4K/aNH/veoj79V7Fco4kDgzvfO3SuoB9PhXrL6tYAid1j/56qAt+g0lgzL+q7WEpRFdl5MvgigNX/PoEofUHgn4oVOK8Yx49sEWxFaXcZuuXTVJu8=
  file: pom.xml
  skip_cleanup: true
  on:
    repo: olevitt/Keycloak-FranceConnect
