language: java
jdk:
  - openjdk8

before_script:
  - mvn -B versions:set -DnewVersion=$TRAVIS_BRANCH

script:
  - mvn -B package

deploy:
  skip_cleanup: true
  provider: releases
  edge: true
  token:
    secure: "KHRESo5KKQs0DYofYhlRqeEcqhVOH/MTHreM0CMC2jA/tC+uQKoPV+Vip5k0cFkrevBosP44ppF0e8ZXFAvOgqoNTwyr7/iNruvxd++4GWmyk2PnAe10eXgs4NWRRVuyuxOvaeLSe/xI4gNUI922Y1K3y1F2mT/QJzVv14QBURvVdDWTtJlHHBbd/GfK9I8lOYiwa0lNBuyvgfb+yGeJP+iegz8cuZ3ZPJDR7/5jaqLQqLP84kkQ8cQ8uRYj43eM3R17RTMv9pwBE/LMZExHTK3ZAOAQFEYHcussEnI1yubPZawlC6gfZ6Qqio168xi8vOEDzoaU4u/cze3Wvqx/gBDeSRrpEPX3cg+tIqRHLmdXt9ePrY6h5uCBl8x8IjhLGg7xpisPTCH8xYeF9lkLF3vxrC7QHrGW2y7jqI/vbmZCdNlUVyNs9gzUtqm2MUpYPkCKwd16+/MIYgmyO4nbdUz3AaNJhKc2yjHjdYKSRacaMdA740nMmSN//TK/j7j9L6A3nZmTVxDgR729EFFY5zgVug786fOMYjllJqxgfpJ5zEvnyGvRekvuyySSyvWPwp3866B05lUy+7MVNzrKbcH+ZPyQTijATzIrnAalVg9P37iEINNy+4Y0SkEKAP5nZ8IpB8geA9m2BCoomyLwQXwvt3wilzF/lyucw+txt6A="
  file_glob: true
  file: target/*.jar
  on:
    tags: true
