language: java

jobs:
  include:
    - stage: GitHub Release
      script: skip
      deploy:
        provider: releases
        token: ${GITHUB_TOKEN}
        file: pom.xml
        skip_cleanup: true
        on:
          branch: setup-ci
